version: "3"

services:

  app:
    image: vision
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
    command: pm2 start process.yml --no-daemon

  mongo:
    image: mongo
    expose:
      - 27017
    volumes:
      - ./data/db:/data/db
